#9chw0z #8ph387 Drone and Rover Simulation
nathangeorge1/beetlebot pull request #113
Opened 2020-07-22 00:57 UTC by RajPShinde

Validation
1. Drone simulation
2. Rover Simulation

2020-07-23 15:48 UTC, Void12987 requested changes

2020-07-23 15:48 UTC, Void12987 commented on README.md
> +7. give navgoals or `nmr launch tests`
We want launching the drone to be as simple as the robot's "nmr launch server" and "nmr launch app".

1. instead of "nmr launch gazebo_drone", do "nmr launch gazebo drone" and "nmr launch gazebo rover" where "nmr launch gazebo" notifies the user to pick a robot arg
2. steps 4-5 should auto-start for the user, not only developers. One option is to update Server.launch.
3. remove these readme notes and tell me in the clickup how to start it

2020-07-23 15:48 UTC, Void12987 commented on conf/nmr.sh
> +				roslaunch nm_navigation Apps.launch robot_type:=drone
we should only have one view--"nmr launch app"--for both robots

2020-07-23 15:48 UTC, Void12987 commented on src/nm_dependencies/nm_navigation/launch/Server.launch
> +
combine Gazebo_rover.launch and Gazebo_drone.launch back into Gazebo.launch. I think less files is easier to maintain

2020-07-23 15:48 UTC, Void12987 commented on src/navigation/launch/flight.launch
> +</launch>
remove this file and instead put the node directly in the launch file

2020-07-23 15:48 UTC, Void12987 commented on src/navigation/src/navigation/takeoff_land.py
> +f=0
generally single letter vars are confusing

2020-07-23 15:48 UTC, Void12987 commented on src/navigation/src/navigation/takeoff_land.py
> +rospy.spin()
move this file to navigation/nodes/cython and follow the procedure within nmr.sh to cythonize this file; ask Vivek for help if unsure

2020-07-23 15:48 UTC, Void12987 commented on src/nm_dependencies/nm_navigation/launch/Apps.launch
> +	</group>
only one rviz

2020-07-23 15:48 UTC, Void12987 commented on src/nm_dependencies/nm_navigation/launch/MoveBase.launch
> +	<arg if="$(eval robot_type == 'drone')" 	name="output_topic" value="cmd_vel" />
Can't we have this just as cmd_vel?

2020-07-23 15:48 UTC, Void12987 commented on src/nm_dependencies/nm_navigation/launch/SLAM.launch
> +	<arg name="sensor_brand"				default="zed" /> <!-- rplidar, generic_stereo, zed -->
instead of "generic_stereo", we want to give the actual sensor's brand. If there is none, then use "gazebo"

2020-07-24 01:10 UTC, RajPShinde commented on src/nm_dependencies/nm_navigation/launch/MoveBase.launch
> +	<arg if="$(eval robot_type == 'drone')" 	name="output_topic" value="cmd_vel" />
cannot be done due to urdf

2020-07-24 01:11 UTC, RajPShinde commented on src/navigation/src/navigation/takeoff_land.py
> +rospy.spin()
will be converted to c++ when implemented on real drone

2020-08-06 20:00 UTC, merged