#426wfe #8gmunt Nm-nav-on-rpi & python gpio driver
nathangeorge1/beetlebot pull request #117
Opened 2020-08-05 16:42 UTC by yashsavle

Created the GPIO driver and tested it with rplidar on Raspberry Pi

2020-08-06 19:55 UTC, Void12987 requested changes

2020-08-06 19:55 UTC, Void12987 commented on src/navigation/src/motor_drivers/RPiGPIODriver/tread_controller.py
> +#!/usr/bin/env python
I believe because there are new python files, we will need to use Cython to create .so files for them and move them to nm_navigation. See nmr.sh lines 187-206.

2020-08-06 19:55 UTC, Void12987 commented on src/nm_dependencies/nm_navigation/conf/NavigationParams_rplidar.yaml
> +# path planning
Instead of having separate parameters, we'll need to use the same ones in NavigationParams. We want the code to be as generic as possible; so having duplication will get confusing.

2020-08-06 19:55 UTC, Void12987 commented on src/nm_dependencies/nm_navigation/launch/SLAM.launch
>  <launch>
The Newmind and Rtabmap Args need to stay the same value as in master, as they are the default values.

To get your stuff working, instead hardcode the args or params you'll need within "	<!-- Rtabmap fpr Lidar -->" on line 89. The goal is for the user to simply change sensor_brand to rplidar and everything you did will work, as opposed to manually changing all those other params.

Because now, stereo camera will not work, even if sensor_brand == "astra"

2020-08-06 19:55 UTC, Void12987 commented on src/nm_dependencies/nm_navigation/launch/Server.launch
> +	<!--"1-90" 						duty cycle value for safe operation-->
shouldn't add any extra args to Server.launch, as this is for users. Instead, keep these in the appropriate lower level file. Even if the user needs to tune these to get the robot working, I'll create a separate task to scale these values accordingly with "drive_speed" and "turn_speed" above.

2020-08-06 19:55 UTC, Void12987 commented on src/nm_dependencies/nm_navigation/launch/internal/default_params/costmap_common_params.yaml
> +  #~ bump:
is this supposed to stay commented out?

2020-08-06 19:55 UTC, Void12987 commented on src/nm_dependencies/nm_navigation/launch/internal/rtabmap.launch
> +  <arg name="frame_id"                default="base_footprint"/>     <!-- Fixed frame id, you may set "base_link" or "base_footprint" if they are published -->
double check that this will not mess with "sensor_brand == zed" on my real robot and "sensor_brand == gazebo"; if you already did, then we're fine.

2020-08-06 20:10 UTC, yashsavle commented on src/nm_dependencies/nm_navigation/conf/NavigationParams_rplidar.yaml
> +# path planning
The rtabmap parameters in NavigationParams is causing problems in generating the map using lidar. So I created a separate file which excludes those parameters and also doesn't affect other sensors like zed.

2020-08-10 16:41 UTC, Void12987 approved these changes

2020-08-10 17:50 UTC, merged