Updating Codebases for task #2w3r58
nathangeorge1/beetlebot pull request #86
Opened 2020-06-05 20:18 UTC by vivekrathi14

This PR validates task #2w3r58 replace robot_pose_ekf with robot_localization.
1. Updated install.sh to install robot_localization package.
2. Updated NavigationDriver.hpp, NavigationDriver.cpp & Server.launch files to include robot_localization code.
3. Added ekf_params.yaml file for robot_localization based configuration for the node.

2020-06-09 19:50 UTC, Void12987 requested changes

2020-06-09 19:50 UTC, Void12987 commented on conf/installNewmind.sh
> +sudo apt-get install ros-kinetic-robot-localization # installs robot_localization package
installNewmind.sh is for developers, but because robot_localization is also for users, it needs to go in install.sh

2020-06-09 19:50 UTC, Void12987 commented on src/nm_dependencies/nm_navigation/launch/Server.launch
> +	<!-- 8. Combining Odometry / Robot Localization-->
generally don't add comments unless needed; we can keep it as "Combining Odometry"

2020-06-09 19:50 UTC, Void12987 commented on src/nm_dependencies/nm_navigation/launch/internal/default_params/ekf_params.yaml
> +odom0: /gazebo/odom
We need the odom sources to be automatically found. Most likely you'll want to set odom0 to the variable for stereo data input in Server.launch

2020-06-10 00:04 UTC, vivekrathi14 commented on conf/installNewmind.sh
> +sudo apt-get install ros-kinetic-robot-localization # installs robot_localization package
I have added the same to install.sh

2020-06-10 00:05 UTC, vivekrathi14 commented on src/nm_dependencies/nm_navigation/launch/Server.launch
> +	<!-- 8. Combining Odometry / Robot Localization-->
Removed the same.

2020-06-10 00:05 UTC, vivekrathi14 commented on src/nm_dependencies/nm_navigation/launch/internal/default_params/ekf_params.yaml
> +odom0: /gazebo/odom
Updated the same.

2020-06-10 21:22 UTC, vivekrathi14 commented on conf/installNewmind.sh
> +sudo apt-get install ros-kinetic-robot-localization # installs robot_localization package
Removed from installNewind.sh

2020-06-15 16:21 UTC, Void12987 commented on src/nm_dependencies/nm_navigation/conf/install.sh
> +sudo apt-get install ros-kinetic-robot-localization # installs robot_localization package
I added a Coding Convention: "Simplify code by merging similar blocks of code with others."

This block of code should be merged with "# install Arduino and ROS dependencies".

It's important to think in terms of readability when forming blocks.

2020-06-15 16:21 UTC, Void12987 commented on conf/installNewmind.sh
> +sudo apt-get install ros-kinetic-robot-localization # installs robot_localization package
I believe this change needs to be removed

2020-06-15 16:21 UTC, Void12987 commented on src/nm_dependencies/nm_navigation/launch/internal/default_params/ekf_params.yaml
> +odom0: example/odom
unless this is needed, I think it can be removed

2020-06-16 00:41 UTC, vivekrathi14 commented on src/nm_dependencies/nm_navigation/conf/install.sh
> +sudo apt-get install ros-kinetic-robot-localization # installs robot_localization package
Resolved this

2020-06-16 00:42 UTC, vivekrathi14 commented on src/nm_dependencies/nm_navigation/launch/internal/default_params/ekf_params.yaml
> +odom0: example/odom
Lets keep it. Removing that gives random problem in navigation, test case 3 is never completed. I did tests 5 times to validate. There is no harm keeping it.

2020-06-16 17:55 UTC, Void12987 commented on src/nm_dependencies/nm_navigation/launch/internal/default_params/ekf_params.yaml
> +odom0: example/odom
ok; generally that's fine, but next time put a comment on that line specifying the bug

2020-06-16 17:56 UTC, Void12987 commented on src/nm_dependencies/nm_navigation/conf/install.sh
> +sudo apt-get install ros-kinetic-robot-localization # installs robot_localization package
Unless I'm mistaken, the latest commit still has robot_localization installed by itself than with the other ROS dependencies.

2020-06-16 19:35 UTC, vivekrathi14 commented on src/nm_dependencies/nm_navigation/conf/install.sh
>  # create catkin_ws, if doesn't exist
I did remove that in the commit id 36b2a9fa9d0c2290af4a623675f902694e925f7a

2020-06-16 19:36 UTC, vivekrathi14 commented on src/nm_dependencies/nm_navigation/conf/install.sh
> +sudo apt-get install ros-kinetic-robot-localization # installs robot_localization package
No, I have removed that. Check commit with id 36b2a9fa9d0c2290af4a623675f902694e925f7a

2020-06-17 18:43 UTC, Void12987 commented on src/nm_dependencies/nm_navigation/conf/install.sh
> +sudo apt-get install ros-kinetic-robot-localization # installs robot_localization package
weird I didn't see that before but I do now

2020-06-17 18:44 UTC, Void12987 approved these changes

2020-06-17 18:49 UTC, merged